# Generated by Django 4.2.18 on 2025-01-27 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('responsibility', models.CharField(choices=[('Wing', 'Wing'), ('Fuselage', 'Fuselage'), ('Tail', 'Tail'), ('Avionics', 'Avionics'), ('Assembly', 'Assembly')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Wing', 'Wing'), ('Fuselage', 'Fuselage'), ('Tail', 'Tail'), ('Avionics', 'Avionics')], max_length=20)),
                ('aircraft', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'AKINCI'), ('KIZILELMA', 'KIZILELMA')], max_length=20)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.team')),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('assembled_at', models.DateTimeField(auto_now_add=True)),
                ('avionics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avionics_parts', to='production.part')),
                ('fuselage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuselage_parts', to='production.part')),
                ('tail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tail_parts', to='production.part')),
                ('wing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wing_parts', to='production.part')),
            ],
        ),
    ]
